# Faça um programa que leia um número inteiro qualquer e mostre na tela a sua tabuada
msg = int(input('Digite um número para ver sua tabuada: '))
print('-'*12)
print(msg, 'x  1 =', (msg*1))
print(msg, 'x  2 =', (msg*2))
print(msg, 'x  3 =', (msg*3))
print(msg, 'x  4 =', (msg*4))
print(msg, 'x  5 =', (msg*5))
print(msg, 'x  6 =', (msg*6))
print(msg, 'x  7 =', (msg*7))
print(msg, 'x  8 =', (msg*8))
print(msg, 'x  9 =', (msg*9))
print(msg, 'x 10 =', (msg*10))
print('-'*12)
